build_targets:
- commands:
  - ./gradlew androidDependencies
  - ./gradlew lint test
  container:
    image: yourbase/yb_ubuntu:18.04
  name: default
  tags:
    project: 5

ci:
  builds:
  - build_target: default
    name: default
dependencies:
  build:
  - java:8.252.09
  - gradle:6.5.1
  - android:latest
